server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health-plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true&noAccessToProcedureBodies=true&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true # flyway 사용여부
    baseline-on-migrate: true # baseline 설정
    baseline-version: 1 # baseline-version을 몇부터 실행할지 설정
    url: jdbc:mysql://localhost:3306/health-plus
    user: root
    password: 1234
    useMysqlMetadata: true # add useMysqlMetadata=true to your jdbc url -> driver will return “MySQL” server type.
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: mysql
    properties:
      hibernate:
        show-sql: false
        default_batch_fetch_size: 1000
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
